### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by AliNemati13** [codedpro/Gamee-Cheats#1]
**Describe the bug**
Program is not working anymore, maybe something is changed in Gamee (Game: Space Orbit).

**Screenshots**
![1](https://github.com/user-attachments/assets/99b730f4-68b5-4568-80b2-00002ebfd412)

**Desktop:**
 - OS: [Windows 11]

**Comment by codedpro** [comment]
Hello the Gamee Algorithms has been changed. i will try to update the tool
